# Generated by Django 5.2.7 on 2025-11-01 13:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lottery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Lottery title', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Lottery description')),
                ('prize_name', models.CharField(help_text='Prize name (e.g., Electric Scooter)', max_length=255)),
                ('prize_image', models.CharField(blank=True, help_text='Prize image URL', max_length=500)),
                ('ticket_price_points', models.IntegerField(default=100, help_text='Points required per ticket')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('ended', 'Ended'), ('drawn', 'Drawn'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('start_date', models.DateTimeField(help_text='Lottery start date')),
                ('end_date', models.DateTimeField(help_text='Lottery end date')),
                ('winner_ticket_id', models.UUIDField(blank=True, help_text='Winning ticket ID', null=True)),
                ('drawn_at', models.DateTimeField(blank=True, help_text='When winner was drawn', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='Admin who created lottery', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_lotteries', to=settings.AUTH_USER_MODEL)),
                ('winner', models.ForeignKey(blank=True, help_text='Winner user', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lottery_wins', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lottery',
                'verbose_name_plural': 'Lotteries',
                'db_table': 'lotteries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LotteryTicket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ticket_count', models.IntegerField(default=1, help_text='Number of tickets purchased')),
                ('points_spent', models.IntegerField(help_text='Total points spent for these tickets')),
                ('purchase_date', models.DateTimeField(auto_now_add=True)),
                ('is_winner', models.BooleanField(default=False, help_text='Whether this ticket won')),
                ('lottery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lottery_tickets', to='points.lottery')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lottery_tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lottery Ticket',
                'verbose_name_plural': 'Lottery Tickets',
                'db_table': 'lottery_tickets',
                'ordering': ['-purchase_date'],
            },
        ),
        migrations.CreateModel(
            name='PointTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.IntegerField(help_text='Point amount (positive for earned, represents deduction for spent)')),
                ('transaction_type', models.CharField(choices=[('earned', 'Earned'), ('spent', 'Spent')], max_length=10)),
                ('source', models.CharField(choices=[('order', 'Order'), ('referral', 'Referral'), ('lottery', 'Lottery'), ('manual', 'Manual'), ('welcome_bonus', 'Welcome Bonus')], help_text='Source of transaction', max_length=20)),
                ('reference_id', models.CharField(blank=True, help_text='Reference to order/referral/lottery ID', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Transaction description')),
                ('balance_after', models.IntegerField(help_text='User balance after this transaction')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Point Transaction',
                'verbose_name_plural': 'Point Transactions',
                'db_table': 'point_transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReferralCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(help_text='Unique referral code', max_length=20, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='referral_code_obj', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Referral Code',
                'verbose_name_plural': 'Referral Codes',
                'db_table': 'referral_codes',
            },
        ),
        migrations.CreateModel(
            name='UserPoints',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('balance', models.IntegerField(default=0, help_text='Current available points')),
                ('lifetime_earned', models.IntegerField(default=0, help_text='Total points earned in lifetime')),
                ('lifetime_spent', models.IntegerField(default=0, help_text='Total points spent in lifetime')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_points', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Points',
                'verbose_name_plural': 'User Points',
                'db_table': 'user_points',
                'ordering': ['-balance'],
            },
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('referral_code', models.CharField(help_text='Referral code used', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('awarded', 'Points Awarded')], default='pending', max_length=20)),
                ('referrer_points_awarded', models.BooleanField(default=False, help_text='Whether referrer received points')),
                ('referred_bonus_awarded', models.BooleanField(default=False, help_text='Whether referred user received welcome bonus')),
                ('completed_at', models.DateTimeField(blank=True, help_text='When referral was completed (first order)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('referred', models.ForeignKey(help_text='User who was referred', on_delete=django.db.models.deletion.CASCADE, related_name='referral_received', to=settings.AUTH_USER_MODEL)),
                ('referrer', models.ForeignKey(help_text='User who gave referral', on_delete=django.db.models.deletion.CASCADE, related_name='referrals_given', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Referral',
                'verbose_name_plural': 'Referrals',
                'db_table': 'referrals',
                'ordering': ['-created_at'],
                'unique_together': {('referrer', 'referred')},
            },
        ),
    ]
