# Generated by Django 5.2.7 on 2025-11-02 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='delivered_weight',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Total weight actually collected/delivered in kg', max_digits=10, null=True),
        ),
    ]
