# Generated by Django 5.2.7 on 2025-11-02 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0002_delivery_delivered_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='reminder_sms_sent',
            field=models.BooleanField(blank=True, default=False, help_text='Whether reminder SMS has been sent 1 hour before delivery'),
        ),
    ]
