# Generated by Django 5.2.7 on 2025-11-03 07:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0003_delivery_reminder_sms_sent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when customer confirmed the delivery', null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='customer_confirmation_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('denied', 'Denied')], default='pending', help_text='Customer confirmation status: pending, confirmed, or denied', max_length=20),
        ),
        migrations.AddField(
            model_name='delivery',
            name='denial_reason',
            field=models.TextField(blank=True, help_text='Reason provided by customer if delivery is denied', null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='license_plate_number',
            field=models.CharField(blank=True, help_text='License plate number of the delivery vehicle (entered by driver when completing delivery)', max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='DeliverySurvey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.IntegerField(default=5, help_text='Rating from 1 to 5 (1=worst, 5=best)')),
                ('comment', models.TextField(blank=True, help_text='Optional comment/feedback from customer')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delivery', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='survey', to='deliveries.delivery')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_surveys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Delivery Survey',
                'verbose_name_plural': 'Delivery Surveys',
                'db_table': 'delivery_surveys',
                'ordering': ['-created_at'],
            },
        ),
    ]
