# Generated by Django 5.2.7 on 2025-11-03 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0004_delivery_confirmed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='cancel_reason',
            field=models.TextField(blank=True, help_text='Reason provided by customer if delivery is cancelled before completion', null=True),
        ),
    ]
