# Generated by Django 5.2.7 on 2025-11-04 07:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0006_deliveryitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WeightShortfall',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('estimated_range', models.CharField(help_text='Weight range selected by customer (e.g., "5-10")', max_length=20)),
                ('minimum_weight', models.DecimalField(decimal_places=2, help_text='Minimum weight for the selected range in kg', max_digits=10)),
                ('delivered_weight', models.DecimalField(decimal_places=2, help_text='Actual weight delivered in kg', max_digits=10)),
                ('shortfall_amount', models.DecimalField(decimal_places=2, help_text='Shortfall amount (negative value) in kg', max_digits=10)),
                ('is_deducted', models.BooleanField(default=False, help_text='Whether this shortfall has been deducted from a subsequent delivery')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deducted_at', models.DateTimeField(blank=True, help_text='When this shortfall was deducted', null=True)),
                ('deducted_from_delivery', models.ForeignKey(blank=True, help_text='Delivery from which this shortfall was deducted', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deducted_shortfalls', to='deliveries.delivery')),
                ('delivery', models.ForeignKey(blank=True, help_text='Delivery that created this shortfall', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shortfall', to='deliveries.delivery')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weight_shortfalls', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Weight Shortfall',
                'verbose_name_plural': 'Weight Shortfalls',
                'db_table': 'weight_shortfalls',
                'ordering': ['-created_at'],
            },
        ),
    ]
