# Generated by Django 5.2.7 on 2025-11-04 07:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0007_weightshortfall'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question_text', models.CharField(help_text='Question text displayed to customer', max_length=500)),
                ('question_type', models.CharField(choices=[('rating', 'Rating (1-5)'), ('text', 'Text Answer'), ('yes_no', 'Yes/No'), ('multiple_choice', 'Multiple Choice')], default='rating', help_text='Type of question', max_length=20)),
                ('options', models.JSONField(blank=True, help_text='Options for multiple choice questions (JSON array)', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this question is currently active')),
                ('order', models.IntegerField(default=0, help_text='Display order (lower numbers appear first)')),
                ('is_required', models.BooleanField(default=False, help_text='Whether this question is required')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Survey Question',
                'verbose_name_plural': 'Survey Questions',
                'db_table': 'survey_questions',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='SurveyAnswer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('answer_value', models.TextField(help_text='Answer value (text, rating number, yes/no, etc.)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='deliveries.deliverysurvey')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='deliveries.surveyquestion')),
            ],
            options={
                'verbose_name': 'Survey Answer',
                'verbose_name_plural': 'Survey Answers',
                'db_table': 'survey_answers',
                'ordering': ['question__order', 'created_at'],
                'unique_together': {('survey', 'question')},
            },
        ),
    ]
