# Generated by Django 5.2.7 on 2025-10-31 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_faq'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSection',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('page', models.CharField(default='home', max_length=50)),
                ('group_name', models.CharField(blank=True, max_length=100)),
                ('version', models.IntegerField(default=0)),
                ('image_path', models.URLField(blank=True)),
                ('setting_type', models.IntegerField(choices=[(0, 'banner'), (1, 'horizontal'), (2, 'countDown'), (3, 'lazy')], default=0)),
                ('expire_date', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('link_url', models.URLField(blank=True)),
                ('locale', models.CharField(default='en', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='products.product')),
            ],
            options={
                'verbose_name': 'Product Section',
                'verbose_name_plural': 'Product Sections',
                'db_table': 'product_sections',
                'indexes': [models.Index(fields=['page', 'is_active'], name='product_sec_page_8aa99f_idx'), models.Index(fields=['group_name', 'is_active'], name='product_sec_group_n_f98d63_idx')],
            },
        ),
    ]
