# Generated by Django 5.2.7 on 2025-11-01 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_productsection'),
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('icon_url', models.CharField(blank=True, max_length=500)),
                ('repair_duration', models.IntegerField(default=0, help_text='Duration in minutes')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('priority', models.IntegerField(default=0)),
                ('locale', models.CharField(default='fa', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='products.problem')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problems', to='products.product')),
            ],
            options={
                'verbose_name': 'Problem',
                'verbose_name_plural': 'Problems',
                'db_table': 'problems',
                'ordering': ['-priority', 'title'],
            },
        ),
    ]
