# Generated by Django 5.2.7 on 2025-11-03 13:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_problem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCode',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=255, unique=True)),
                ('status', models.CharField(choices=[('unused', 'Unused'), ('assigned', 'Assigned'), ('used', 'Used')], default='unused', max_length=10)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_codes', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codes', to='products.product')),
            ],
            options={
                'verbose_name': 'Product Code',
                'verbose_name_plural': 'Product Codes',
                'db_table': 'product_codes',
                'indexes': [models.Index(fields=['product', 'status'], name='product_cod_product_56d284_idx')],
            },
        ),
    ]
