# Generated by Django 5.2.7 on 2025-11-08 07:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_productcode'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Parent problem (optional). Use to create hierarchical problem categories. Leave empty for top-level problems.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='products.problem'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='priority',
            field=models.IntegerField(default=0, help_text='Display priority (higher number = shown first). 0 = lowest priority. Used for ordering: problems are sorted by priority (descending), then by title.'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='product',
            field=models.ForeignKey(help_text='Product this problem is associated with. Required.', on_delete=django.db.models.deletion.CASCADE, related_name='problems', to='products.product'),
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('image_url', models.CharField(blank=True, max_length=500)),
                ('locale', models.CharField(default='fa', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Brand',
                'verbose_name_plural': 'Brands',
                'db_table': 'brands',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name', 'is_active'], name='brands_name_6c8691_idx'), models.Index(fields=['locale', 'is_active'], name='brands_locale_f52204_idx')],
            },
        ),
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='products.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bookmark',
                'verbose_name_plural': 'Bookmarks',
                'db_table': 'bookmarks',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='bookmarks_user_id_2ce2db_idx'), models.Index(fields=['product'], name='bookmarks_product_744b5f_idx')],
                'unique_together': {('user', 'product')},
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item_id', models.UUIDField(help_text='ID of the liked item (product, blog post, etc.)')),
                ('item_type', models.CharField(choices=[('product', 'Product'), ('item', 'Item'), ('blog', 'Blog Post'), ('comment', 'Comment')], default='product', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Like',
                'verbose_name_plural': 'Likes',
                'db_table': 'likes',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'item_type', 'created_at'], name='likes_user_id_6eb34a_idx'), models.Index(fields=['item_id', 'item_type'], name='likes_item_id_846dd9_idx')],
                'unique_together': {('user', 'item_id', 'item_type')},
            },
        ),
    ]
