# Generated by Django 5.2.7 on 2025-11-08 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_problem_parent_alter_problem_priority_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='type',
            field=models.IntegerField(default=0, help_text='Category type (0-32)'),
        ),
    ]
