# Generated by Django 5.2.7 on 2025-11-16 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_add_category_type_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='in_stock',
            field=models.IntegerField(default=0, help_text='Available inventory/stock quantity'),
        ),
    ]
