# Generated by Django 5.2.7 on 2025-11-10 06:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Localization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(help_text='Translation key', max_length=255)),
                ('value', models.TextField(help_text='Translated text')),
                ('resource_set', models.CharField(help_text='Resource set name (e.g., "common", "errors")', max_length=100)),
                ('locale', models.CharField(default='en', help_text='Language code (e.g., "en", "fa")', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Localization',
                'verbose_name_plural': 'Localizations',
                'db_table': 'localizations',
                'ordering': ['resource_set', 'key', 'locale'],
                'indexes': [models.Index(fields=['resource_set', 'locale', 'is_active'], name='localizatio_resourc_972930_idx'), models.Index(fields=['key', 'resource_set'], name='localizatio_key_837cbc_idx'), models.Index(fields=['locale', 'is_active'], name='localizatio_locale_f73393_idx')],
                'unique_together': {('key', 'resource_set', 'locale')},
            },
        ),
        migrations.CreateModel(
            name='MailTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Template name/identifier', max_length=255, unique=True)),
                ('subject', models.CharField(help_text='Email subject line', max_length=500)),
                ('body', models.TextField(help_text='Email body (HTML or plain text)')),
                ('template_type', models.CharField(help_text='Template type (e.g., "welcome", "order_confirmation", "password_reset")', max_length=50)),
                ('locale', models.CharField(default='en', help_text='Language code (e.g., "en", "fa")', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Mail Template',
                'verbose_name_plural': 'Mail Templates',
                'db_table': 'mail_templates',
                'ordering': ['name', 'locale'],
                'indexes': [models.Index(fields=['name', 'locale', 'is_active'], name='mail_templa_name_573ea7_idx'), models.Index(fields=['template_type', 'is_active'], name='mail_templa_templat_7dfcbe_idx')],
                'unique_together': {('name', 'locale')},
            },
        ),
    ]
