# Generated by Django 5.2.7 on 2025-10-28 18:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('totalPrice', models.IntegerField(default=0)),
                ('status', models.IntegerField(default=0)),
                ('userId', models.CharField(blank=True, max_length=255)),
                ('address1', models.TextField(blank=True)),
                ('address2', models.TextField(blank=True)),
                ('phone1', models.CharField(blank=True, max_length=15)),
                ('phone2', models.CharField(blank=True, max_length=15)),
                ('createOrderDate', models.DateTimeField(auto_now_add=True)),
                ('submitPriceDate', models.DateTimeField(blank=True, null=True)),
                ('sendToPostDate', models.DateTimeField(blank=True, null=True)),
                ('postStateNumber', models.CharField(blank=True, max_length=100)),
                ('paymentTrackingCode', models.CharField(blank=True, max_length=100)),
                ('userFullName', models.CharField(blank=True, max_length=255)),
                ('userPhoneNumber', models.CharField(blank=True, max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'db_table': 'orders',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('productName', models.CharField(max_length=255)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unitPrice', models.IntegerField(default=0)),
                ('totalPrice', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderItems', to='orders.order')),
            ],
            options={
                'verbose_name': 'Order Item',
                'verbose_name_plural': 'Order Items',
                'db_table': 'order_items',
            },
        ),
    ]
