# Generated by Django 5.2.7 on 2025-11-02 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_latitude_order_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Weight in kg for waste/recyclable items', max_digits=10, null=True),
        ),
    ]
