# Generated by Django 5.2.7 on 2025-01-XX XX:XX

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_orderitem_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='estimated_weight_range',
            field=models.CharField(blank=True, help_text='Estimated weight range selected by customer (e.g., "2-5", "5-10", "10-20" in kg)', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='preferred_delivery_date',
            field=models.DateTimeField(blank=True, help_text='Preferred delivery date and time selected by customer', null=True),
        ),
    ]

