"""
Django settings for zistino_backend project.

Generated by 'django-admin startproject' using Django 5.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import os
from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY', default='django-insecure-change-this-in-production')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=True, cast=bool)

ALLOWED_HOSTS = config('ALLOWED_HOSTS', default=['*'], cast=lambda v: [s.strip() for s in v.split(',')])


# Application definition

DJANGO_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

THIRD_PARTY_APPS = [
    'rest_framework',
    'rest_framework.authtoken',  # For Token authentication
    'corsheaders',
    'django_filters',
    'drf_spectacular',
]

LOCAL_APPS = [
    'zistino_apps.authentication',
    'zistino_apps.users',
    'zistino_apps.orders',
    'zistino_apps.products',
    'zistino_apps.deliveries',
    'zistino_apps.payments',
    'zistino_apps.notifications',
    'zistino_apps.baskets',
    'zistino_apps.configurations',
    'zistino_apps.content',
    'zistino_apps.points',
    'zistino_apps.compatibility',  # Compatibility layer for Flutter apps
]

INSTALLED_APPS = DJANGO_APPS + THIRD_PARTY_APPS + LOCAL_APPS

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# Disable automatic trailing slash appending to match old Swagger format
APPEND_SLASH = False

ROOT_URLCONF = 'zistino_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'zistino_backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

# PostgreSQL Database Configuration
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': config('DB_NAME', default='zistino_db'),
        'USER': config('DB_USER', default='postgres'),
        'PASSWORD': config('DB_PASSWORD', default=''),
        'HOST': config('DB_HOST', default='localhost'),
        'PORT': config('DB_PORT', default='5432'),
    }
}

# SQLite fallback (for development/testing only - comment out when using PostgreSQL):
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Tehran'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Django REST Framework settings
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'zistino_apps.compatibility.authentication.JWTAuthentication',  # JWT authentication for compatibility
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    # Custom exception handler for standardized error responses
    'EXCEPTION_HANDLER': 'zistino_apps.compatibility.exceptions.compatibility_exception_handler',
}

# drf- settings
SPECTACULAR_SETTINGS = {
    'TITLE': 'Zistino Backend API',
    'DESCRIPTION': 'API documentation for Zistino driver app and related services.',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'SERVE_PERMISSIONS': ['rest_framework.permissions.AllowAny'],

    # پروتکل‌ها
    'SCHEMES': ['http', 'https'],

    # سرورها
    'SERVERS': [
        {"url": "https://zistino-latest.onrender.com", "description": "Render production"},
        {"url": "http://127.0.0.1:8000", "description": "Local development server"},
    ],

    # 🔹 تعریف نوع‌های احراز هویت که در Swagger دیده می‌شوند
    'SECURITY_SCHEMES': {
        # همون سشن جنگو
        'cookieAuth': {
            'type': 'apiKey',
            'in': 'cookie',
            'name': 'sessionid',
        },
        # JWT ما
        'tokenAuth': {
            'type': 'apiKey',
            'in': 'header',
            'name': 'Authorization',
            'description': 'JWT token. Example: Bearer {your_token}',
        },
    },

    # 🔹 پیش‌فرض همه‌ی endpointها tokenAuth لازم دارند
    'SECURITY': [
        {'tokenAuth': []},
    ],
}


# CORS settings
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "http://localhost:5173",
    "http://127.0.0.1:5173",
    "http://localhost:8080",
    "http://127.0.0.1:8080",
    "http://localhost:8000",
    "http://127.0.0.1:8000",
    "https://zistino-latest.onrender.com",
]

# Allow all origins in development (for Swagger UI and testing)
if DEBUG:
    CORS_ALLOW_ALL_ORIGINS = True
else:
    CORS_ALLOW_ALL_ORIGINS = False
    CORS_ALLOWED_ORIGINS = [ 
       "https://zistino-latest.onrender.com",  
   ]

CORS_ALLOW_CREDENTIALS = True

# Allow all methods and headers for development
CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]

CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
    'tenant',
]

# Custom User Model
AUTH_USER_MODEL = 'authentication.User'

# SMS Service Configuration - MeliPayamak (Priority Provider)
MELIPAYAMAK_USERNAME = config('MELIPAYAMAK_USERNAME', default='')
MELIPAYAMAK_API_KEY = config('MELIPAYAMAK_API_KEY', default='')  # API Key used as password
# MELIPAYAMAK_API_URL = config('MELIPAYAMAK_API_URL', default='https://rest.payamak-panel.com/api/SendSMS/SendSMS')
MELIPAYAMAK_SENDER = config('MELIPAYAMAK_SENDER', default='')  # Sender number

# SMS Service Configuration - Mizban SMS (Fallback Provider)
# MIZBAN_SMS_USERNAME = config('MIZBAN_SMS_USERNAME', default='')
# MIZBAN_SMS_PASSWORD = config('MIZBAN_SMS_PASSWORD', default='')
# MIZBAN_SMS_API_URL = config('MIZBAN_SMS_API_URL', default='https://services.mizbansms.com/api/Message/SendMessage')
# MIZBAN_SMS_SENDER = config('MIZBAN_SMS_SENDER', default='')  # Sender number/ID (if required)
# MIZBAN_SMS_AUTH_TOKEN = config('MIZBAN_SMS_AUTH_TOKEN', default='')  # Authorization token/API key

# Legacy SMS settings (kept for backward compatibility)
SMS_SERVICE_API_KEY = config('SMS_SERVICE_API_KEY', default='')
SMS_SERVICE_URL = config('SMS_SERVICE_URL', default='')

# File Upload Settings
FILE_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024  # 10MB
DATA_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024  # 10MB

# Cache Configuration (Redis)
CACHES = {
    'default': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': config('REDIS_URL', default='redis://127.0.0.1:6379/1'),
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
        }
    }
}

# Celery Configuration
CELERY_BROKER_URL = config('CELERY_BROKER_URL', default='redis://localhost:6379')
CELERY_RESULT_BACKEND = config('CELERY_RESULT_BACKEND', default='redis://localhost:6379')
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE

# Celery Beat Schedule (for periodic tasks)
CELERY_BEAT_SCHEDULE = {
    'check-delivery-reminders': {
        'task': 'zistino_apps.deliveries.tasks.check_and_send_delivery_reminders',
        'schedule': 15.0,  # Run every 15 minutes
        # 'schedule': crontab(minute='*/15'),  # Alternative: every 15 minutes using crontab
    },
}
