# Generated by Django 5.2.7 on 2025-11-10 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compatibility', '0005_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleClaim',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('claim_type', models.CharField(default='permission', help_text='Type of claim (e.g., permission)', max_length=100)),
                ('claim_value', models.CharField(help_text='Claim value (e.g., Permissions.Products.View)', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Claim description', null=True)),
                ('group', models.CharField(blank=True, help_text='Claim group name', max_length=255, null=True)),
                ('selected', models.BooleanField(default=False, help_text='Whether this claim is selected')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.ForeignKey(help_text='Role this claim belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='compatibility.role')),
            ],
            options={
                'verbose_name': 'Role Claim',
                'verbose_name_plural': 'Role Claims',
                'db_table': 'role_claims',
                'ordering': ['claim_value'],
                'indexes': [models.Index(fields=['role', 'claim_type'], name='role_claims_role_id_4fdcb7_idx'), models.Index(fields=['claim_value'], name='role_claims_claim_v_e9d530_idx')],
            },
        ),
    ]
