# Generated by Django 5.2.7 on 2025-11-10 11:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compatibility', '0007_tenant'),
    ]

    operations = [
        # Drop the existing table and recreate with UUID
        migrations.RunSQL(
            sql=[
                "DROP TABLE IF EXISTS tenants CASCADE;",
            ],
            reverse_sql=[
                "DROP TABLE IF EXISTS tenants CASCADE;",
            ]
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Tenant name', max_length=255)),
                ('key', models.CharField(help_text='Tenant key/identifier', max_length=255, unique=True)),
                ('admin_email', models.EmailField(blank=True, help_text='Admin email for tenant', max_length=254, null=True)),
                ('connection_string', models.TextField(blank=True, help_text='Database connection string', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether tenant is active')),
                ('extended_expiry_date', models.DateTimeField(blank=True, help_text='Extended expiry date for subscription (validUpto)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tenant',
                'verbose_name_plural': 'Tenants',
                'db_table': 'tenants',
                'ordering': ['name'],
            },
        ),
    ]
