# Generated by Django 5.2.7 on 2025-11-10 13:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compatibility', '0008_alter_tenant_extended_expiry_date_alter_tenant_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('subject', models.CharField(help_text='Ticket subject', max_length=255)),
                ('status', models.IntegerField(default=0, help_text='Ticket status (0=open, 1=closed, etc.)')),
                ('priority', models.IntegerField(default=0, help_text='Ticket priority (0=low, 1=medium, 2=high, 3=urgent)')),
                ('category_id', models.IntegerField(default=0, help_text='Category ID')),
                ('item_id', models.IntegerField(default=0, help_text='Item ID')),
                ('item_type', models.IntegerField(default=0, help_text='Item type')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='Ticket creator', on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ticket',
                'verbose_name_plural': 'Tickets',
                'db_table': 'tickets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketMessage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.TextField(help_text='Message content')),
                ('type', models.IntegerField(default=0, help_text='Message type (0=user, 1=admin, etc.)')),
                ('status', models.IntegerField(default=0, help_text='Message status')),
                ('response_message_id', models.IntegerField(blank=True, default=None, help_text='Response to message ID', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ticket', models.ForeignKey(help_text='Related ticket', on_delete=django.db.models.deletion.CASCADE, related_name='ticket_messages', to='compatibility.ticket')),
                ('user', models.ForeignKey(help_text='Message sender', on_delete=django.db.models.deletion.CASCADE, related_name='ticket_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ticket Message',
                'verbose_name_plural': 'Ticket Messages',
                'db_table': 'ticket_messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketMessageDocument',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('file_url', models.CharField(help_text='File URL', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ticket_message', models.ForeignKey(help_text='Related ticket message', on_delete=django.db.models.deletion.CASCADE, related_name='ticket_message_documents', to='compatibility.ticketmessage')),
            ],
            options={
                'verbose_name': 'Ticket Message Document',
                'verbose_name_plural': 'Ticket Message Documents',
                'db_table': 'ticket_message_documents',
                'ordering': ['created_at'],
            },
        ),
    ]
