# Generated by Django 5.2.7 on 2025-11-10 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compatibility', '0009_ticket_ticketmessage_ticketmessagedocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='category_id',
            field=models.IntegerField(blank=True, default=None, help_text='Category ID', null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='item_id',
            field=models.IntegerField(blank=True, default=None, help_text='Item ID', null=True),
        ),
    ]
