# Generated by Django 5.2.7 on 2025-11-11 05:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compatibility', '0010_alter_ticket_category_id_alter_ticket_item_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUsMessage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('firstName', models.CharField(db_column='first_name', max_length=255)),
                ('lastName', models.CharField(db_column='last_name', max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('jsonExt', models.TextField(blank=True, db_column='json_ext', help_text='JSON extension field for additional data', null=True)),
                ('type', models.IntegerField(choices=[(0, 'General Inquiry'), (1, 'Support Request'), (2, 'Complaint'), (3, 'Suggestion'), (4, 'Other')], default=0)),
                ('responseStatus', models.IntegerField(choices=[(0, 'Pending'), (1, 'In Progress'), (2, 'Resolved'), (3, 'Closed')], db_column='response_status', default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Contact Us Message',
                'verbose_name_plural': 'Contact Us Messages',
                'db_table': 'contact_us_messages',
                'ordering': ['-created_at'],
            },
        ),
    ]
