# Generated by Django 5.2.7 on 2025-10-31 18:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('zone', models.CharField(max_length=255)),
                ('zonepath', models.CharField(blank=True, max_length=500)),
                ('description', models.TextField(blank=True)),
                ('address', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Zone',
                'verbose_name_plural': 'Zones',
                'db_table': 'zones',
            },
        ),
        migrations.CreateModel(
            name='UserZone',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('last_modified_on', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_zones', to=settings.AUTH_USER_MODEL)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_zones', to='users.zone')),
            ],
            options={
                'verbose_name': 'User Zone',
                'verbose_name_plural': 'User Zones',
                'db_table': 'user_zones',
                'indexes': [models.Index(fields=['zone'], name='user_zones_zone_id_9c1e1d_idx')],
                'unique_together': {('user', 'zone')},
            },
        ),
    ]
