# Generated by Django 5.2.7 on 2025-11-01 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_zone_userzone'),
    ]

    operations = [
        migrations.AddField(
            model_name='zone',
            name='center_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Zone center point latitude', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='zone',
            name='center_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Zone center point longitude', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='zone',
            name='radius_km',
            field=models.DecimalField(decimal_places=2, default=10.0, help_text='Zone radius in kilometers', max_digits=10),
        ),
    ]
