# Generated by Django 5.2.7 on 2025-11-08 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_zone_center_latitude_zone_center_longitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='fax',
            field=models.CharField(blank=True, help_text='Fax number', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='title',
            field=models.CharField(blank=True, help_text='Address title/label', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='website',
            field=models.URLField(blank=True, help_text='Website URL', null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='port',
            field=models.IntegerField(default=0, help_text='Network port number for GPS device communication. 0 = not configured (use default port). Common ports: 80 (HTTP), 443 (HTTPS), 8080 (alternative HTTP), 5027 (TCP), etc.'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='protocol',
            field=models.CharField(blank=True, help_text='GPS device communication protocol (e.g., TCP, UDP, HTTP, HTTPS)', max_length=50),
        ),
    ]
