"""
Custom JWT Authentication for compatibility with old Swagger format.
Validates JWT tokens generated by the tokens endpoint.
"""
from rest_framework import authentication, exceptions
from django.conf import settings
import jwt
from zistino_apps.authentication.models import User


class JWTAuthentication(authentication.BaseAuthentication):
    """
    Custom JWT authentication that validates tokens generated by the tokens endpoint.
    Extracts user ID from JWT payload and returns the user.
    """
    
    def authenticate(self, request):
        """
        Authenticate the request using JWT token from Authorization header.
        Returns (user, token) tuple if valid, None otherwise.
        """
        auth_header = request.META.get('HTTP_AUTHORIZATION', '')
        
        if not auth_header:
            return None
        
        # Check if it's a Bearer token
        if not auth_header.startswith('Bearer '):
            return None
        
        # Extract token
        token = auth_header.split(' ')[1]
        
        try:
            # Decode JWT token
            secret_key = getattr(settings, 'SECRET_KEY', 'django-insecure-change-this-in-production')
            payload = jwt.decode(token, secret_key, algorithms=['HS256'])
            
            # Extract user ID from payload (using the claim name from token generation)
            user_id_claim = 'http://schemas.xmlsoap.org/ws/2005/05/identity/claims/nameidentifier'
            user_id = payload.get(user_id_claim)
            
            if not user_id:
                # Try alternative claim names
                user_id = payload.get('user_id') or payload.get('sub') or payload.get('id')
            
            if not user_id:
                raise exceptions.AuthenticationFailed('Invalid token: no user ID found')
            
            # Get user
            try:
                user = User.objects.get(id=user_id)
            except User.DoesNotExist:
                raise exceptions.AuthenticationFailed('User not found')
            
            # Check if user is active
            if not user.is_active:
                raise exceptions.AuthenticationFailed('User is inactive')
            
            return (user, token)
            
        except jwt.ExpiredSignatureError:
            raise exceptions.AuthenticationFailed('Token has expired')
        except jwt.DecodeError:
            raise exceptions.AuthenticationFailed('Invalid token')
        except jwt.InvalidTokenError:
            raise exceptions.AuthenticationFailed('Invalid token')
        except Exception as e:
            raise exceptions.AuthenticationFailed(f'Authentication failed: {str(e)}')

