# Generated by Django 5.2.7 on 2025-10-31 06:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_order_userid_order_external_user_id_and_more'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BasketDiscount',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('basket', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='discount', to='orders.basket')),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='basket_discounts', to='payments.coupon')),
            ],
            options={
                'verbose_name': 'Basket Discount',
                'verbose_name_plural': 'Basket Discounts',
                'db_table': 'basket_discounts',
            },
        ),
    ]
