# Generated by Django 5.2.7 on 2025-11-01 12:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_basketdiscount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DepositRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount to deposit in Rials', max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('reference_id', models.CharField(blank=True, help_text='Bank receipt or reference number (optional)', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Additional notes or description')),
                ('verified_at', models.DateTimeField(blank=True, help_text='When admin verified the deposit', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transaction', models.OneToOneField(blank=True, help_text='Transaction created when deposit is approved', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deposit_request', to='payments.transaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposit_requests', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, help_text='Admin user who verified this deposit', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_deposits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Deposit Request',
                'verbose_name_plural': 'Deposit Requests',
                'db_table': 'deposit_requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
